// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShirtsManagament.API.Data;

#nullable disable

namespace ShirtsManagament.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShirtsManagament.API.Models.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "My brand",
                            Color = "Black",
                            Gender = "M",
                            Price = 200m,
                            Size = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "My brand",
                            Color = "Yellow",
                            Gender = "M",
                            Price = 250m,
                            Size = 12.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Another brand",
                            Color = "Blue",
                            Gender = "F",
                            Price = 180m,
                            Size = 8.0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Another brand",
                            Gender = "F",
                            Price = 200m,
                            Size = 9.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
